### ISSUE TITLE
Question: which project is likely to be maintained in the future?

### ISSUE THREAD

**Issue by rs2** [pallets/cachelib#10]
This repo is nearly identical to [sh4nks/flask-caching](https://github.com/sh4nks/flask-caching).

Which is more likely to be maintained in the future? E.g. the former features a ready `conda` recipe and a package.

**Comment by davidism** [comment]
We don't support conda in general. The two projects are separate, so this question doesn't make much sense. Sorry I can't be more specific.

**Comment by fuglede** [comment]
@davidism Would you be directly opposed to the package being available on [conda-forge](https://conda-forge.org/)? If not, I could go ahead and do a bit of the legwork (which in practice boils down to very little). And might you be interested in maintaining such a package (which in practice boils down to simply clicking a button every time you deploy to pypi, as everything else is automated)?

**Comment by davidism** [comment]
Why does this need to be on conda-forge? There is nothing conda-specific (such as other languages, compiling, etc.), and conda already allows installing PyPI packages with pip. Sorry, but I have no desire to work on conda, as my experience is that it makes things harder for my workflow (and new contributors at sprints), not better. I guess I can't stop you, and it looks like others have put other Pallets projects on there already, but I won't provide support.

**Comment by fuglede** [comment]
Thanks for getting back so fast!

The main use case would be for using cachelib in other conda packages: You're right that you can easily install packages with pip in a conda environment, but when you're building a new package (be it for an application or a library), all dependencies need to be available as conda packages.

In any case, thanks for noting the expected level of support; that's certainly fair!
