### ISSUE TITLE
Universal timestamp storage in FileSystemCache

### ISSUE THREAD

**Issue by subnix** [pallets/cachelib#121]
FileSystemCache implies that a serializer is framed, but some serializers (like json) are not framed and don’t support multiple load/dump from single file descriptor, since it can't determine message borders. This complicates serializer integration.
https://github.com/pallets/cachelib/blob/3777a15cc01d55544bd63d6ffe7e680a823b58fa/src/cachelib/file.py#L231-L237
https://github.com/pallets/cachelib/blob/3777a15cc01d55544bd63d6ffe7e680a823b58fa/src/cachelib/file.py#L192-L195

Sure, framing proxy may be implemented, but this will lead to storage and processing overheads. Since other backends don’t use framed serialization, may be we could implement serialization in a universal (non framed) way?
For example, via `struct`:
```python
with os.fdopen(fd, "wb") as f:
    f.write(struct.pack("I", timeout))
    self.serializer.dump(value, f)

with self._safe_stream_open(filename, "rb") as f: 
     pickle_time = struct.unpack("I", f.read(4))
     if pickle_time == 0 or pickle_time >= time(): 
         return self.serializer.load(f) 
```
`struct` also reduces storage overhead (4 bytes vs 17 bytes via pickle).
Another solution is to store metadata in extended attributes ([`xattr`](https://man7.org/linux/man-pages/man7/xattr.7.html) in linux/darwin or EA in windows). Modern filesystems (like xfs or ext4) have huge inode size (256 bytes by default), so 4 bytes won’t be a problem, but if we don’t fit into current inode, new inode will be created. Theoretically, this also should reduce file operations for expired keys since we work only with inodes, but additional research and benchmarks are required and I'm not sure about portability.

**Comment by northernSage** [comment]
Thanks for the detailed write up @subnix. The way _FileSystemCache_ currently handles timestamps has been bothering me since #11 so this is quite interesting. So far I haven't worked with python's `struct` module that much, but from a quick read up it seems like the way to go (straight forward to implement while keeping portability). I would be glad to review a PR if you find the time to write it (just let me know here). 👍🏻
