### ISSUE TITLE
The use of os.replace(...) does not work in Python 2

### ISSUE THREAD

**Issue by rayluo** [pallets/cachelib#14]
It has been reported in [here](https://github.com/pallets/cachelib/pull/12#commitcomment-40259945) and [there](https://github.com/Azure-Samples/ms-identity-python-webapp/issues/52) that [the `os.replace(...)` used by cachelib](https://github.com/pallets/cachelib/pull/12/files#diff-f04a97b31520db402767843a530a3f118317ee6aec4b4ba4cb9ea6b6196f3bbaR158) is [not supported in Python 2](https://docs.python.org/2.7/library/os.html). Do we consider to have a fallback implementation for Python 2? Something like this? I can provide a PR if necessary.

```python
try:
    os.replace(tmp, filename)
except AttributeError:  # Python 2 workaround
    try:
        os.remove(filename)
    except:
        pass
    os.rename(tmp, filename)
```

**Comment by davidism** [comment]
Python 2 is no longer supported.

**Comment by rayluo** [comment]
Just for the record, that Azure web app sample does NOT need any upgrade to be used with Python 3. It is already written in a way that it does not use any Python3-or-Python2-only syntax. I was merely shifting the conversation from that issue into its root cause here, to let you decide whether you want to satisfy your customer.
