### ISSUE TITLE
Missing file count updates in `get()` and `has()`

### ISSUE THREAD

**Issue by hkcomori** [pallets/cachelib#20]
After `os.remove()` in `FileSystemCache.get()` and `FileSystemCache.has()`, `self._update_count()` should be called.

**Comment by northernSage** [comment]
Yeah, that seems to be the case. I'll probably roll it into #13 since it's a simple fix. Nice catch 👍🏻

**Comment by northernSage** [comment]
done @hkcomori 🚀

**Comment by hkcomori** [comment]
@northernSage nice work!
