### ISSUE TITLE
Tests corresponding to test_memcached_cache.py file are failing on the Linux platform.

### ISSUE THREAD

**Issue by odidev** [pallets/cachelib#39]
I am building and testing cachelib on the Linux platform. I have followed the below steps to build and test cachelib:

**BUILD STEPS:**
~~~
$ git clone https://github.com/pallets/cachelib
$ cd cachelib
$ python3 -m venv env
$ . env/bin/activate
$ pip install -e . -r requirements/dev.txt
$ pre-commit install
~~~
**TEST STEPS:**
~~~
$ pytest
~~~
 
Build is successful, but tests corresponding to test_memcached_cache.py file are failing. Below is the short test summary after pytest:
~~~
E  TimeoutError: The provided start pattern server listening could not be matched within the specified time interval of 120 seconds

env/lib/python3.9/site-packages/xprocess.py:284: TimeoutError
======================================================== short test summary info ========================================================
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_clear - TimeoutError: The provided start pattern server listening could ...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_set_get - TimeoutError: The provided start pattern server listening coul...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_set_get_many - TimeoutError: The provided start pattern server listening...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_get_dict - TimeoutError: The provided start pattern server listening cou...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_delete - TimeoutError: The provided start pattern server listening could...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_delete_many - TimeoutError: The provided start pattern server listening ...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_add - TimeoutError: The provided start pattern server listening could no...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_inc_dec - TimeoutError: The provided start pattern server listening coul...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_expiration - TimeoutError: The provided start pattern server listening c...
ERROR tests/test_memcached_cache.py::TestMemcachedCache::test_has - TimeoutError: The provided start pattern server listening could no...
========================================= 34 passed, 1 skipped, 10 errors in 137.85s (0:02:17) ==========================================
~~~

Please find the detailed error logs here: [cachelib_memcache_failing_tests_logs.txt](https://github.com/pallets/cachelib/files/6599327/cachelib_memcache_failing_tests_logs.txt)

Memcache was not installed on my system, so these tests were getting skipped. 
Then I successfully installed **memcache, libmemcached-dev, zlib1g-dev, libmemcached-tools, memcached from the apt repo; and installed pylibmc, pymemcache and python-memcached using pip**. But the issue is always the same, tests are failing.  
I have restarted and checked the memcache service using `service memcache restart`...tests are failing even after memcache is in active state.

Can you please provide me with the pointers on how to pass these failing tests? 
Please guide me if some more information is required.

Environment:

- Python version: 3.8
- Cachelib version: master branch

**Comment by northernSage** [comment]
I have just tests this on Fedora, Ubuntu, MacOS and Windows and wasn't able to reproduce the issue. Apparently, pytest-xprocess is failing to match the given process starting patter, when this happens it's usually an issue with the environment so we will have to find out what is wrong. Could you please post the version of memcached installed in your system (`memcached --version`) and of all the python packages installed in your virtual environment (`pip freeze` command)? One other thing, are you able to start memcached manually in your shell with `memcached -vv`? Also, i'll need to know which linux distro you are on, since I'll mirror your environment using docker and try to reproduce the issue there. @odidev

**Comment by odidev** [comment]
Hi @northernSage .....Thank you for the response.

I ran the build and test commands in a Sudo user mode, and now all tests are passing. I think the issue was in running commands as a root user.

I will close this issue now as the tests are passing.

**Comment by davidism** [comment]
> ran the build and test commands in a Sudo user mode

Absolutely never do this, for this or any other library. Installing to the system (as root) should always be a separate step from building or testing, neither of which need root.
