### ISSUE TITLE
FileSystemCache warns about FileNotFoundError exception

### ISSUE THREAD

**Issue by harpener** [pallets/cachelib#62]
FileSystemCache logs a warning with FileNotFoundError exception if working with files that do not exist.

To reproduce, simply call [FileSystemCache.get](https://github.com/pallets/cachelib/blob/main/src/cachelib/file.py#L172) on non-existing file (a new key).

I think there should be no such logs, because this is the most common case - when you work with cache, you always try to get the value first and set the value only if it does not exist. There can be a lot of such logs and they pollute the log.

Also, looking at the code, I don't think it affects only [FileSystemCache.get](https://github.com/pallets/cachelib/blob/main/src/cachelib/file.py#L172). I would consider other places with these logs as well, because consider situation where two processes start pruning cached files and collide, trying to delete the same file twice.

Environment:

- Python version: 3.8
- CacheLib version: 0.3.0

Thank you for your opinion on this.

**Comment by northernSage** [comment]
Hey @harpener, thanks for taking the time to let us know about this.

The log calls were added in #51 to let the user know about possible corrupt cache files due to external factors (e.g. process crashes and such) and I unfortunately didn't consider how it would pollute the logs. I'm not sure we should remove the logs altogether but I can write a PR adding a filter if it would help.

**Comment by harpener** [comment]
Hi @northernSage, I studied the changes a bit, so I understand why the logging was added. I think it is okay to point out unexpected errors, but, much like the change in https://github.com/pallets/cachelib/pull/53, I think `FileNotFoundError` in particular should be ignored. Thanks for the anwer.

**Comment by dignajar** [comment]
I have the same "issue", waiting for the new release! thank you

**Comment by northernSage** [comment]
Fixed in #69 and the next release won't take long to come out. Closing this for now 😉
