### ISSUE TITLE
cachelib writing string values with odd encoding

### ISSUE THREAD

**Issue by pcgeek86** [pallets/cachelib#7]
I'm using `cachelib` from Python 3.7 to write simple string values into Redis, with the `set()` method. 

```
from cachelib import RedisCache

cache = RedisCache()
cache.set('FirstName', 'Trevor')
```

Using the `redis-cli`, you can see the value when it's set from `cachelib` (first), versus set with the `redis-cli` itself (second).

```
127.0.0.1:6379> get FirstName
"!\x80\x03X\b\x00\x00\x00Trevorq\x00."
127.0.0.1:6379> set FirstName trevor
OK
127.0.0.1:6379> get FirstName
"trevor"
```

Is there an explanation for why cachelib is writing data in this format?

**Comment by ThiefMaster** [comment]
https://github.com/pallets/cachelib/blob/master/cachelib/redis.py#L59-L60

**Comment by pcgeek86** [comment]
Gotcha, I guess it must be the pickling. I need to spend a little time understanding how that module works. Thanks!
