### ISSUE TITLE
Breaking changes on 0.4.0

### ISSUE THREAD

**Issue by sumeshdubey-squla** [pallets/cachelib#81]
There is a type hinting on line 31 of redis.py for the host to be string and also if host is not string (in case of rediscluster) then in that case the self.__client is not available on line 51 of redis.py as the "else:" is removed. For everyone who are sending rediscluster client in host, this change will break their application

Environment:

- Python version: 3.7
- CacheLib version: 0.4.0

**Comment by northernSage** [comment]
Hey @sumeshdubey-squla, thanks for taking the tine to let us know about this. I'll look into the issue and probably submit a patch as soon as I get home (currently at work)

**Comment by sumeshdubey-squla** [comment]
@northernSage thanks a lot for the quick response and fixing this in no time
