### ISSUE TITLE
PermissionError [WinError 5] [Errno 13] with FileSystemCache on Windows 10 

### ISSUE THREAD

**Issue by mybooc** [pallets/cachelib#85]
Using set() and get() of FileSystemCache raises exceptions on Windows 10 when called very fast. 

PermissionError: [Errno 13] Permission denied ...
PermissionError: [WinError 5] Access is denied ...

There are no errors when running the same script on Ubuntu 20.04.

How to replicate (optional increase range):

```
import cachelib
import threading

fsc = cachelib.file.FileSystemCache('.')

def set_get(i):
    fsc.set('key', 'val')
    val = fsc.get('key')

for i in range(10):
    t = threading.Thread(target=set_get, args=(i,))
    t.start()

```
Randomly generates tracebacks like:

WARNING:root:Exception raised while handling cache file '.\3c6e0b8a9c15224a8228b9a98ca1531d'
Traceback (most recent call last):
  File "C:\Users\User\...\lib\site-packages\cachelib\file.py", line 183, in get
    with open(filename, "rb") as f:
PermissionError: [Errno 13] Permission denied: '.\\3c6e0b8a9c15224a8228b9a98ca1531d'

WARNING:root:Exception raised while handling cache file '.\3c6e0b8a9c15224a8228b9a98ca1531d'
Traceback (most recent call last):
  File "C:\Users\User\...\lib\site-packages\cachelib\file.py", line 228, in set
    os.replace(tmp, filename)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\User\\python3.8\\venvs\\imapclient\\cachelib_test\\tmpop5jfhp8.__wz_cache' -> '.\\3c6e0b8a9c15224a8228b9a98ca1531d'

Expected behavior is no errors. I bounced into this with Flask-Session using Cachelib FileSystemCache on Windows 10 when sessions got lost/not updated. Maybe it has to do with the fact that Windows 10 is running in a VirtualBox(?). I did not try this on a native Windows 10 system. Maybe it has to do with the implementation of os.replace on Windows(?).

Environment:

- CacheLib version: 0.4.1
- Windows 10 Pro is running in VirtualBox on Ubuntu 20.04. 
- Python version: Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32.
- The script is running in a virtual environment.

**Comment by lrpatterson** [comment]
I am also getting this issue in Windows.  

```

WARNING:root:Exception raised while handling cache file '.......\m928c483i879\1d3cce8dc82cb9568a5e3c3246c84f98'
Traceback (most recent call last):
  File "......\lib\site-packages\cachelib\file.py", line 228, in set
    os.replace(tmp, filename)
PermissionError: [WinError 5] Access is denied: '....\\m928c483i879\\tmpqdj9zac3.__wz_cache' -> '......\\m928c483i879\\1d3cce8dc82cb9568a5e3c3246c84f98'

```

**Comment by PC-LoadLetter** [comment]
I can recreate this issue in Windows 10. It is intermittent. The issue seems to be that Windows 10 doesn't have enough time to close the tempfile before os.replace is called. The file exists and file permissions are satisfied. I tested the timing issue on my system and the error no longer occurs when a 50 millisecond delay is inserted between closing the tempfile and calling os.replace.

**Comment by mybooc** [comment]
> I can recreate this issue in Windows 10. It is intermittent. The issue seems to be that Windows 10 doesn't have enough time to close the tempfile before os.replace is called. The file exists and file permissions are satisfied. I tested the timing issue on my system and the error no longer occurs when a 50 millisecond delay is inserted between closing the tempfile and calling os.replace.

Thank you for reporting this. It is not enough to insert a delay, you should also do retries. See for example concurrency_safe_rename: 

https://github.com/flennerhag/mlens/blob/master/mlens/externals/joblib/backports.py

**Comment by northernSage** [comment]
Thanks all for reporting the problem and presenting possible solutions. IMO delay + retries seem like a feasible solution. If anyone feels like tackling this just let me know by commenting here, I would be happy to review a PR and help out wherever I can. If no one volunteers I'll go ahead and write a fix for this once time allows (it might take a while 😞...)

**Comment by mybooc** [comment]
For Windows (os.name == 'nt'), with os.replace() you need to capture winerror=5 (Access is Denied), see my previous post for an example, and with all other calls accessing the os.replace() file at least IOError errno=13 (Permission denied). Set max sleep time to at least 10 seconds. Made a quick fix myself, unfortunately too busy to help here at the moment. You may also want to check the issue i opened and closed here:

https://bugs.python.org/issue46003
