### ISSUE TITLE
Magic number in SimpleCache and FileSystemCache

### ISSUE THREAD

**Issue by dAnjou** [pallets/cachelib#9]
The [pruning](https://github.com/pallets/cachelib/blob/159ee3974bd71b939840ed302cbdf03fd7b16767/cachelib/simple.py#L36) contains a magic number, it seems it deletes only every third entry: `idx % 3`.

Does anyone know the intention behind this?

I traced it back to the very beginning, there is no info there: https://github.com/mitsuhiko/zine/commit/3502607828b0f6ed136ed9ae74a09fa10f78a3ed#diff-b0794f264f02b7241cc1088d07e16659

**Comment by ThiefMaster** [comment]
A wild guess would be to make it clear that older cache entries can disappear at any time, and applications should support it.

**Comment by northernSage** [comment]
Thanks for reporting the issue. Since #26 has changed the prunning I'll go ahead and close this for now. Fell free to reopen it if necessary.
