### ISSUE TITLE
Serializer support for Memcached backend

### ISSUE THREAD

**Issue by elnelsonperez** [pallets/cachelib#96]
I believe memcached is the only backend who did not get a default serializer here https://github.com/pallets/cachelib/pull/63.
It this a conscious decision?

**Comment by northernSage** [comment]
Serialization for `memcached` is not handled by `cachelib` like for other cache clients (such as `redis` or `uwsgi`) and it's currently done in packages/modules that we use for bindings like `pylibmc`, `libmc`, etc (most use pickle natively if I remember correctly). So, while related, adding support for custom serializers to `cachelib.memcached` will entail changes of a different nature when compared to what we see in #63. 

I'm open to ideas here, but for now I plan on releasing #63 as is and revisit this in the future. @elnelsonperez

**Comment by subnix** [comment]
There is also one important thing - pylibmc and libmc has no ability to disable unpickling. [GAE memcache](https://github.com/GoogleCloudPlatform/appengine-python-standard/blob/530a54b0fc0eb74d9dc29b19b7c4cdfab0556ebc/src/google/appengine/api/memcache/__init__.py#L346) and [python-memcached](https://github.com/linsomniac/python-memcached/blob/bad41222379102e3f18f6f2f7be3ee608de6fbff/memcache.py#L161) allows to pass pickler/unpickler.
